# Generated by Django 2.0.4 on 2018-04-25 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='课程名称')),
                ('code', models.CharField(max_length=300, verbose_name='课程代码')),
                ('introduction', models.TextField(verbose_name='课程简介')),
                ('picture', models.ImageField(upload_to='', verbose_name='课程封面')),
                ('term', models.CharField(max_length=300, verbose_name='学期代码')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('level', models.CharField(choices=[('chapter', '章'), ('section', '节'), ('unit', '单元')], max_length=7, verbose_name='层次类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabuses', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='cms.Course', verbose_name='所属课程')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cms.Syllabus', verbose_name='上级节点')),
            ],
            options={
                'verbose_name_plural': '大纲',
            },
        ),
    ]
