# Generated by Django 2.0.4 on 2018-04-26 03:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_auto_20180425_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(verbose_name='完成情况')),
                ('complate_at', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='cms.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name_plural': '进度',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='成绩项')),
                ('score', models.CharField(max_length=300, verbose_name='得分')),
                ('grader', models.CharField(max_length=300, verbose_name='评分人')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cms.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name_plural': '成绩',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='姓名')),
                ('sno', models.CharField(max_length=300, verbose_name='学号')),
                ('role', models.CharField(max_length=300, verbose_name='角色')),
                ('joined', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cms.Course', verbose_name='所属课程')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name_plural': '成员',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='选项内容')),
                ('correct', models.BooleanField(verbose_name='是否答案')),
            ],
            options={
                'verbose_name_plural': '题目选项',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('subject', ckeditor.fields.RichTextField(verbose_name='题干')),
                ('qtype', models.CharField(max_length=300, verbose_name='题型')),
                ('score', models.CharField(max_length=300, verbose_name='得分')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cms.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name_plural': '题目',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cms.Question', verbose_name='所属题目'),
        ),
        migrations.AddField(
            model_name='grade',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cms.Member', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='completion',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='cms.Member', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='completion',
            name='syllabus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='cms.Syllabus', verbose_name='所属课程'),
        ),
    ]
