# Generated by Django 2.0.4 on 2018-06-06 10:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300, verbose_name='代码')),
                ('title', models.CharField(max_length=300, verbose_name='课程名称')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='作业描述')),
                ('attachment', models.FileField(upload_to='', verbose_name='附件')),
                ('begin', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='截止时间')),
                ('term', models.CharField(max_length=300, verbose_name='学期代码')),
                ('score_type', models.CharField(choices=[('scale', '评级'), ('point', '评分')], max_length=300, verbose_name='作业类型')),
                ('pass_line', models.CharField(max_length=300, verbose_name='及格线')),
            ],
            options={
                'verbose_name_plural': '作业',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=300, verbose_name='学号')),
                ('name', models.CharField(max_length=300, verbose_name='姓名')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='作业内容')),
                ('attachment', models.FileField(upload_to='', verbose_name='附件')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('score', models.CharField(max_length=300, verbose_name='得分')),
                ('correction', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='批改')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tams.Assignment', verbose_name='所属作业')),
            ],
            options={
                'verbose_name_plural': '作业结果',
            },
        ),
    ]
