# Generated by Django 2.0.4 on 2018-06-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='term',
        ),
    ]
