# Generated by Django 2.0.4 on 2018-06-14 12:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tams', '0002_remove_assignment_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=300, verbose_name='学号')),
                ('name', models.CharField(max_length=300, verbose_name='姓名')),
                ('answer', models.CharField(max_length=300, verbose_name='答案')),
                ('correct', models.BooleanField(verbose_name='是否正确')),
            ],
            options={
                'verbose_name_plural': '答卷',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300, verbose_name='代码')),
                ('title', models.CharField(max_length=300, verbose_name='测验名称')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='描述')),
                ('begin', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='截止时间')),
                ('limit', models.IntegerField(verbose_name='时间限制')),
                ('pass_line', models.CharField(max_length=300, verbose_name='及格线')),
                ('retry', models.IntegerField(verbose_name='重试次数')),
            ],
            options={
                'verbose_name_plural': '测验',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('subject', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='题干')),
                ('qtype', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judgment', '判断题')], max_length=300, verbose_name='题型')),
                ('score', models.CharField(max_length=300, verbose_name='得分')),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tams.Exam', verbose_name='所属测验')),
            ],
            options={
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='选项内容')),
                ('correct', models.BooleanField(verbose_name='是否答案')),
                ('examPaper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tams.ExamPaper', verbose_name='所属题目')),
            ],
            options={
                'verbose_name_plural': '试题选项',
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='作业描述'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=300, verbose_name='作业名称'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='attachment',
            field=models.FileField(blank=True, upload_to='', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='作业内容'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='correction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='批改'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='score',
            field=models.CharField(blank=True, max_length=300, verbose_name='得分'),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='examPaper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tams.ExamPaper', verbose_name='所属题目'),
        ),
    ]
