# Generated by Django 2.0.3 on 2018-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='文本标题')),
                ('content', models.TextField(verbose_name='文本内容')),
            ],
            options={
                'verbose_name_plural': '文本资源',
            },
        ),
        migrations.CreateModel(
            name='ResAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=300)),
            ],
        ),
    ]
