# Generated by Django 2.0.3 on 2018-03-22 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resaudio',
            options={'verbose_name_plural': '音频资源'},
        ),
        migrations.AlterModelOptions(
            name='resdocument',
            options={'verbose_name_plural': '文档资源'},
        ),
        migrations.AlterModelOptions(
            name='reslink',
            options={'verbose_name_plural': '链接资源'},
        ),
        migrations.AlterModelOptions(
            name='respicture',
            options={'verbose_name_plural': '图片资源'},
        ),
        migrations.AlterModelOptions(
            name='resvideo',
            options={'verbose_name_plural': '视频资源'},
        ),
        migrations.AddField(
            model_name='resarticle',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='res_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resarticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respicture',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='res_pictures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respicture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
