# Generated by Django 2.0.3 on 2018-03-27 12:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0002_auto_20180322_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resarticle',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='res_articles', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='resarticle',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文本内容'),
        ),
        migrations.AlterField(
            model_name='respicture',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='res_pictures', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='respicture',
            name='path',
            field=models.CharField(max_length=300, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='respicture',
            name='title',
            field=models.CharField(max_length=300, verbose_name='图片标题'),
        ),
    ]
