# Generated by Django 2.0.3 on 2018-03-27 13:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_resource', '0003_auto_20180327_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='resdocument',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='res_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='resdocument',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文本内容'),
        ),
        migrations.AlterField(
            model_name='resdocument',
            name='path',
            field=models.FileField(upload_to='', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='resdocument',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
    ]
