# Generated by Django 2.0.3 on 2018-03-28 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_resource', '0004_auto_20180327_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='reslink',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='res_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reslink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resaudio',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='reslink',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='reslink',
            name='url',
            field=models.CharField(max_length=300, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='resvideo',
            name='title',
            field=models.CharField(max_length=300, verbose_name='标题'),
        ),
    ]
